### ISSUE TITLE
SemVer Commit Check

### ISSUE THREAD

**Issue by JohnnyIrvin** [JohnnyIrvin/Python-Template#6]
Checks commits in PR for SemVer Convention compliance

**Is your feature request related to a problem? Please describe.**
The current development process allows for committing changes with arbitrary messages, which can lead to problems when determining changes for release. 

**Describe the solution you'd like**
The proposed solution is a GitHub workflow that checks each commit message made on a pull request branch against the conventional commit specification to ensure that the message follows SemVer Convention format.

**Describe alternatives you've considered**
We could manually review each commit message made in pull requests, but this would require more time and effort from reviewers.

Example Job (Generated by AI)
```yml
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Check for SemVer compliance
      run: |
        for commit in $(git log --pretty=format:"%s" HEAD~1..HEAD); do
          if ! [[ $commit =~ ^(feat|fix|perf|chore|docs|style|refactor|test|build):[[:space:]].*$ ]]; then
            echo "Invalid commit message format for SemVer"
            exit 1
          fi
        done
 ```
